api:
  klusterai:
    base_url: "${KLUSTERAI_BASE_URL}"
    model: "${KLUSTERAI_MODEL}"
  github:
    owner: "${GITHUB_ORG}"
  slack:
    channel: "${SLACK_CHANNEL}"

processing:
  limits:
    max_input_tokens_per_request: ${MAX_INPUT_TOKENS_PER_REQUEST}
  batch:
    cleanup: ${BATCH_CLEANUP}
    keep_days: ${KEEP_DAYS}
    generated_files_directory: "batch_files"

runtime:
  debug: ${DEBUG} 