klusterai:
  base_url: "http://api.kluster.ai/v1"
  model: "klusterai/Meta-Llama-3.1-405B-Instruct-Turbo"

github:
  owner: "ADD-YOUR-OWNER-HERE"
  repo: "YOUR-REPO-HERE" # remove this line if you want to process all repos

slack:
  channel: "ADD-YOUR-CHANNEL-HERE"

limits:
  input_tokens_per_request: 100000 