api:
  klusterai:
    base_url: "https://api.kluster.ai/v1"
    model: "klusterai/Meta-Llama-3.1-405B-Instruct-Turbo"
  github:
    owner: your-org-name
    repo: your-repo-name #remove for all repos
  slack:
    channel: your-channel-name

processing:
  limits:
    max_input_tokens_per_request: 100000
  batch:
    cleanup: true
    keep_days: 7
    generated_files_directory: batch_files
  history:
    default_lookback_hours: 24
    use_last_run_file: true

runtime:
  debug: false