api:
  klusterai:
    base_url: "http://api.kluster.ai/v1"
    model: "klusterai/Meta-Llama-3.1-405B-Instruct-Turbo"
  github:
    owner: your-org-name
    repo: optional-specific-repo  # remove for all repos
  slack:
    channel: your-channel-name

processing:
  limits:
    max_input_tokens_per_request: 100000
  batch:
    cleanup: true
    keep_days: 7
    generated_files_directory: batch_files

runtime:
  debug: true